# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\"\"\n\rCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"H\n\x13\x43ourseFilterRequest\x12\x13\n\x0bimplementer\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0e\n\x06search\x18\x03 \x01(\t\"_\n\x06Lesson\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x61y_of_week\x18\x02 \x01(\t\x12\x12\n\nstring_day\x18\x03 \x01(\t\x12\x1c\n\x14string_time_interval\x18\x04 \x01(\t\"\xa7\x01\n\x12\x43ourseFullResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1d\n\x15is_prerecorded_course\x18\x04 \x01(\x08\x12\x13\n\x0bimplementer\x18\x05 \x01(\t\x12\r\n\x05roles\x18\x06 \x03(\t\x12\x1f\n\x07lessons\x18\x07 \x03(\x0b\x32\x0e.course.Lesson\"F\n\x0b\x43ourseShort\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x15is_prerecorded_course\x18\x03 \x01(\x08\":\n\x12\x43ourseListResponse\x12$\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x13.course.CourseShort\"&\n\x14\x43ourseExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xe3\x01\n\rCourseService\x12\x44\n\x0fget_course_info\x12\x15.course.CourseRequest\x1a\x1a.course.CourseFullResponse\x12\x46\n\x0bget_courses\x12\x1b.course.CourseFilterRequest\x1a\x1a.course.CourseListResponse\x12\x44\n\rexists_course\x12\x15.course.CourseRequest\x1a\x1c.course.CourseExistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COURSEREQUEST']._serialized_start=24
  _globals['_COURSEREQUEST']._serialized_end=58
  _globals['_COURSEFILTERREQUEST']._serialized_start=60
  _globals['_COURSEFILTERREQUEST']._serialized_end=132
  _globals['_LESSON']._serialized_start=134
  _globals['_LESSON']._serialized_end=229
  _globals['_COURSEFULLRESPONSE']._serialized_start=232
  _globals['_COURSEFULLRESPONSE']._serialized_end=399
  _globals['_COURSESHORT']._serialized_start=401
  _globals['_COURSESHORT']._serialized_end=471
  _globals['_COURSELISTRESPONSE']._serialized_start=473
  _globals['_COURSELISTRESPONSE']._serialized_end=531
  _globals['_COURSEEXISTSRESPONSE']._serialized_start=533
  _globals['_COURSEEXISTSRESPONSE']._serialized_end=571
  _globals['_COURSESERVICE']._serialized_start=574
  _globals['_COURSESERVICE']._serialized_end=801
# @@protoc_insertion_point(module_scope)
